// Mock data for demonstration
import { User, Resource, Match, AnalyticsData } from './types';

export const mockCurrentUser: User = {
  id: '1',
  name: 'Arjun Sharma',
  email: 'arjun@example.com',
  college: 'IIT Delhi',
  skills: ['React', 'TypeScript', 'Node.js', 'Python', 'Machine Learning'],
  interests: ['AI/ML', 'Web Development', 'Hackathons', 'Open Source'],
  experience: 'Intermediate',
  bio: 'Passionate developer interested in building AI-powered applications. Love hackathons and collaborative projects!',
  availability: 'Weekends',
  profileImage: 'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?q=80&w=256&h=256&auto=format&fit=crop',
};

export const mockUsers: User[] = [
  {
    id: '2',
    name: 'Priya Patel',
    email: 'priya@example.com',
    college: 'BITS Pilani',
    skills: ['Python', 'Django', 'PostgreSQL', 'Docker', 'AWS'],
    interests: ['Backend Development', 'DevOps', 'Cloud Computing'],
    experience: 'Advanced',
    bio: 'Backend enthusiast with a passion for scalable systems.',
    availability: 'Part-time',
    profileImage: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?q=80&w=256&h=256&auto=format&fit=crop',
  },
  {
    id: '3',
    name: 'Rahul Verma',
    email: 'rahul@example.com',
    college: 'NIT Trichy',
    skills: ['UI/UX Design', 'Figma', 'React', 'Tailwind CSS', 'Framer Motion'],
    interests: ['Design', 'Frontend Development', 'Animation'],
    experience: 'Intermediate',
    bio: 'Designer who codes. Creating beautiful user experiences.',
    availability: 'Weekends',
    profileImage: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?q=80&w=256&h=256&auto=format&fit=crop',
  },
  {
    id: '4',
    name: 'Sneha Gupta',
    email: 'sneha@example.com',
    college: 'IIT Bombay',
    skills: ['Machine Learning', 'TensorFlow', 'Python', 'Data Science', 'NLP'],
    interests: ['AI/ML', 'Research', 'Data Science'],
    experience: 'Advanced',
    bio: 'AI researcher working on NLP projects. Looking for ML collaborators.',
    availability: 'Full-time',
    profileImage: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?q=80&w=256&h=256&auto=format&fit=crop',
  },
  {
    id: '5',
    name: 'Karthik Reddy',
    email: 'karthik@example.com',
    college: 'VIT Vellore',
    skills: ['Flutter', 'Dart', 'Firebase', 'Mobile Development'],
    interests: ['Mobile Apps', 'Startups', 'Product Development'],
    experience: 'Intermediate',
    bio: 'Mobile app developer building the next big thing.',
    availability: 'Part-time',
    profileImage: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?q=80&w=256&h=256&auto=format&fit=crop',
  },
  {
    id: '6',
    name: 'Aisha Khan',
    email: 'aisha@example.com',
    college: 'IIT Madras',
    skills: ['React', 'Next.js', 'TypeScript', 'GraphQL', 'Node.js'],
    interests: ['Full Stack Development', 'Web3', 'Open Source'],
    experience: 'Advanced',
    bio: 'Full-stack developer passionate about modern web technologies and decentralized systems.',
    availability: 'Weekends',
    profileImage: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?q=80&w=256&h=256&auto=format&fit=crop',
  },
  {
    id: '7',
    name: 'Rohan Singh',
    email: 'rohan@example.com',
    college: 'DTU Delhi',
    skills: ['Java', 'Spring Boot', 'Microservices', 'Kubernetes', 'MongoDB'],
    interests: ['Backend Development', 'System Design', 'Distributed Systems'],
    experience: 'Intermediate',
    bio: 'Backend developer exploring microservices architecture and cloud-native applications.',
    availability: 'Part-time',
    profileImage: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?q=80&w=256&h=256&auto=format&fit=crop',
  },
  {
    id: '8',
    name: 'Ananya Das',
    email: 'ananya@example.com',
    college: 'IIT Kharagpur',
    skills: ['React Native', 'iOS', 'Swift', 'Firebase', 'Redux'],
    interests: ['Mobile Development', 'UI/UX', 'Hackathons'],
    experience: 'Intermediate',
    bio: 'Mobile developer who loves building cross-platform apps and winning hackathons.',
    profileImage: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?q=80&w=256&h=256&auto=format&fit=crop',
    availability: 'Weekends',
  },
  {
    id: '9',
    name: 'Vikram Mehta',
    email: 'vikram@example.com',
    college: 'IIIT Hyderabad',
    skills: ['Python', 'Data Science', 'Pandas', 'Scikit-learn', 'Tableau'],
    interests: ['Data Analytics', 'Machine Learning', 'Business Intelligence'],
    experience: 'Advanced',
    bio: 'Data scientist passionate about extracting insights from complex datasets.',
    profileImage: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?q=80&w=256&h=256&auto=format&fit=crop',
    availability: 'Full-time',
  },
  {
    id: '10',
    name: 'Neha Joshi',
    email: 'neha@example.com',
    college: 'NIT Surathkal',
    skills: ['Angular', 'TypeScript', 'RxJS', 'HTML', 'CSS'],
    interests: ['Frontend Development', 'Web Design', 'Accessibility'],
    experience: 'Intermediate',
    bio: 'Frontend developer focused on creating accessible and responsive web applications.',
    profileImage: 'https://images.unsplash.com/photo-1554151228-14d9def656e4?q=80&w=256&h=256&auto=format&fit=crop',
    availability: 'Part-time',
  },
  {
    id: '11',
    name: 'Siddharth Iyer',
    email: 'siddharth@example.com',
    college: 'IIT Kanpur',
    skills: ['Go', 'Rust', 'Docker', 'Kubernetes', 'gRPC'],
    interests: ['Backend Development', 'Performance Optimization', 'Cloud Native'],
    experience: 'Advanced',
    bio: 'Systems programmer interested in high-performance backend services.',
    profileImage: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?q=80&w=256&h=256&auto=format&fit=crop',
    availability: 'Weekends',
  },
  {
    id: '12',
    name: 'Meera Nair',
    email: 'meera@example.com',
    college: 'Manipal Institute',
    skills: ['Vue.js', 'Nuxt.js', 'JavaScript', 'Sass', 'Figma'],
    interests: ['Frontend Development', 'Design Systems', 'Animation'],
    experience: 'Intermediate',
    bio: 'Frontend developer with an eye for design and smooth animations.',
    profileImage: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?q=80&w=256&h=256&auto=format&fit=crop',
    availability: 'Part-time',
  },
  {
    id: '13',
    name: 'Aryan Kumar',
    email: 'aryan@example.com',
    college: 'NSUT Delhi',
    skills: ['C++', 'Competitive Programming', 'Algorithms', 'Data Structures'],
    interests: ['Competitive Programming', 'Problem Solving', 'Hackathons'],
    experience: 'Advanced',
    bio: 'Competitive programmer with multiple ICPC medals. Love solving complex algorithmic challenges.',
    profileImage: 'https://images.unsplash.com/photo-1504257404462-db0960dccde5?q=80&w=256&h=256&auto=format&fit=crop',
    availability: 'Weekends',
  },
  {
    id: '14',
    name: 'Ishita Sharma',
    email: 'ishita@example.com',
    college: 'BIT Mesra',
    skills: ['Blockchain', 'Solidity', 'Ethereum', 'Web3.js', 'Smart Contracts'],
    interests: ['Blockchain', 'Web3', 'DeFi'],
    experience: 'Intermediate',
    bio: 'Blockchain developer building the future of decentralized applications.',
    profileImage: 'https://images.unsplash.com/photo-1519345182560-3f2917c472ef?q=80&w=256&h=256&auto=format&fit=crop',
    availability: 'Part-time',
  },
  {
    id: '15',
    name: 'Aarav Desai',
    email: 'aarav@example.com',
    college: 'IIT Roorkee',
    skills: ['Cybersecurity', 'Ethical Hacking', 'Penetration Testing', 'Network Security'],
    interests: ['Security', 'CTF Competitions', 'Bug Bounty'],
    experience: 'Advanced',
    bio: 'Security enthusiast passionate about finding vulnerabilities and making software secure.',
    profileImage: 'https://images.unsplash.com/photo-1531427186611-ecfd6d936c79?q=80&w=256&h=256&auto=format&fit=crop',
    availability: 'Weekends',
  },
];

export const mockResources: Resource[] = [
  {
    id: 'r1',
    title: 'React Official Documentation',
    link: 'https://react.dev',
    category: 'Docs',
    tags: ['React', 'JavaScript', 'Frontend'],
    upvotes: 245,
    createdBy: 'Admin',
    createdAt: new Date('2024-01-15'),
    description: 'Official React documentation with hooks and best practices',
  },
  {
    id: 'r2',
    title: 'Full Stack Open - Modern Web Development',
    link: 'https://fullstackopen.com',
    category: 'Course',
    tags: ['React', 'Node.js', 'Full Stack'],
    upvotes: 189,
    createdBy: 'Priya Patel',
    createdAt: new Date('2024-02-01'),
    description: 'Comprehensive full-stack course from University of Helsinki',
  },
  {
    id: 'r3',
    title: 'Fireship - 100 Seconds Series',
    link: 'https://youtube.com/@Fireship',
    category: 'YouTube',
    tags: ['Quick Learning', 'Web Development', 'Various'],
    upvotes: 312,
    createdBy: 'Rahul Verma',
    createdAt: new Date('2024-01-20'),
    description: 'Quick, engaging tech explanations in 100 seconds',
  },
  {
    id: 'r4',
    title: 'TensorFlow Machine Learning Crash Course',
    link: 'https://developers.google.com/machine-learning/crash-course',
    category: 'Course',
    tags: ['Machine Learning', 'TensorFlow', 'Python'],
    upvotes: 278,
    createdBy: 'Sneha Gupta',
    createdAt: new Date('2024-01-10'),
    description: 'Google\'s fast-paced ML introduction with TensorFlow APIs',
  },
  {
    id: 'r5',
    title: 'Awesome React - Curated List',
    link: 'https://github.com/enaqx/awesome-react',
    category: 'GitHub',
    tags: ['React', 'Resources', 'Awesome List'],
    upvotes: 156,
    createdBy: 'Arjun Sharma',
    createdAt: new Date('2024-02-05'),
    description: 'A collection of awesome things regarding React ecosystem',
  },
  {
    id: 'r6',
    title: 'TypeScript Deep Dive',
    link: 'https://basarat.gitbook.io/typescript',
    category: 'Docs',
    tags: ['TypeScript', 'JavaScript', 'Programming'],
    upvotes: 201,
    createdBy: 'Karthik Reddy',
    createdAt: new Date('2024-01-25'),
    description: 'The definitive guide to TypeScript',
  },
  {
    id: 'r7',
    title: 'CS50 - Introduction to Computer Science',
    link: 'https://cs50.harvard.edu',
    category: 'Course',
    tags: ['Computer Science', 'Algorithms', 'Programming'],
    upvotes: 423,
    createdBy: 'Admin',
    createdAt: new Date('2024-01-05'),
    description: 'Harvard\'s legendary introduction to computer science course',
  },
  {
    id: 'r8',
    title: 'The Odin Project - Full Stack JavaScript',
    link: 'https://theodinproject.com',
    category: 'Course',
    tags: ['JavaScript', 'Full Stack', 'Web Development'],
    upvotes: 287,
    createdBy: 'Priya Patel',
    createdAt: new Date('2024-01-18'),
    description: 'Free full-stack curriculum with projects and community support',
  },
  {
    id: 'r9',
    title: 'FreeCodeCamp - Responsive Web Design',
    link: 'https://freecodecamp.org',
    category: 'Course',
    tags: ['HTML', 'CSS', 'Responsive Design', 'Frontend'],
    upvotes: 356,
    createdBy: 'Rahul Verma',
    createdAt: new Date('2024-02-10'),
    description: 'Learn responsive web design with hands-on projects',
  },
  {
    id: 'r10',
    title: 'Traversy Media - Web Development Crash Courses',
    link: 'https://youtube.com/@TraversyMedia',
    category: 'YouTube',
    tags: ['Web Development', 'Tutorials', 'Full Stack'],
    upvotes: 298,
    createdBy: 'Arjun Sharma',
    createdAt: new Date('2024-01-22'),
    description: 'Comprehensive web development tutorials and crash courses',
  },
  {
    id: 'r11',
    title: 'System Design Primer',
    link: 'https://github.com/donnemartin/system-design-primer',
    category: 'GitHub',
    tags: ['System Design', 'Architecture', 'Scalability'],
    upvotes: 512,
    createdBy: 'Sneha Gupta',
    createdAt: new Date('2024-01-08'),
    description: 'Learn how to design large-scale systems. Prep for system design interview',
  },
  {
    id: 'r12',
    title: 'LeetCode Patterns - DSA Guide',
    link: 'https://seanprashad.com/leetcode-patterns',
    category: 'Docs',
    tags: ['Algorithms', 'Data Structures', 'Interview Prep'],
    upvotes: 445,
    createdBy: 'Karthik Reddy',
    createdAt: new Date('2024-02-03'),
    description: 'Comprehensive patterns for solving coding interview problems',
  },
  {
    id: 'r13',
    title: 'Fast.ai - Practical Deep Learning',
    link: 'https://fast.ai',
    category: 'Course',
    tags: ['Deep Learning', 'AI', 'PyTorch', 'Neural Networks'],
    upvotes: 389,
    createdBy: 'Sneha Gupta',
    createdAt: new Date('2024-01-12'),
    description: 'Top-down teaching approach to deep learning for coders',
  },
  {
    id: 'r14',
    title: 'Docker Documentation & Getting Started',
    link: 'https://docs.docker.com',
    category: 'Docs',
    tags: ['Docker', 'DevOps', 'Containers', 'Deployment'],
    upvotes: 223,
    createdBy: 'Priya Patel',
    createdAt: new Date('2024-02-08'),
    description: 'Complete guide to containerization with Docker',
  },
  {
    id: 'r15',
    title: 'Web Dev Simplified - Modern JavaScript',
    link: 'https://youtube.com/@WebDevSimplified',
    category: 'YouTube',
    tags: ['JavaScript', 'Web Development', 'Tutorials'],
    upvotes: 267,
    createdBy: 'Rahul Verma',
    createdAt: new Date('2024-01-28'),
    description: 'Clear, concise JavaScript and web development tutorials',
  },
  {
    id: 'r16',
    title: 'Awesome Python - Ultimate Resource List',
    link: 'https://github.com/vinta/awesome-python',
    category: 'GitHub',
    tags: ['Python', 'Resources', 'Frameworks', 'Libraries'],
    upvotes: 334,
    createdBy: 'Arjun Sharma',
    createdAt: new Date('2024-01-30'),
    description: 'Curated list of awesome Python frameworks, libraries and software',
  },
  {
    id: 'r17',
    title: 'Next.js Documentation & Learn',
    link: 'https://nextjs.org/learn',
    category: 'Docs',
    tags: ['Next.js', 'React', 'SSR', 'Full Stack'],
    upvotes: 298,
    createdBy: 'Priya Patel',
    createdAt: new Date('2024-02-12'),
    description: 'Official Next.js interactive tutorial and documentation',
  },
  {
    id: 'r18',
    title: 'Tailwind CSS Master Class',
    link: 'https://tailwindcss.com/docs',
    category: 'Docs',
    tags: ['Tailwind CSS', 'CSS', 'Styling', 'Frontend'],
    upvotes: 276,
    createdBy: 'Rahul Verma',
    createdAt: new Date('2024-01-16'),
    description: 'Rapidly build modern websites with utility-first CSS',
  },
  {
    id: 'r19',
    title: 'Tech With Tim - Python & Game Development',
    link: 'https://youtube.com/@TechWithTim',
    category: 'YouTube',
    tags: ['Python', 'Game Development', 'Pygame', 'Projects'],
    upvotes: 245,
    createdBy: 'Karthik Reddy',
    createdAt: new Date('2024-02-14'),
    description: 'Python tutorials, projects, and game development guides',
  },
  {
    id: 'r20',
    title: 'Clean Code - Uncle Bob\'s Blog',
    link: 'https://blog.cleancoder.com',
    category: 'Blog',
    tags: ['Clean Code', 'Best Practices', 'Software Engineering'],
    upvotes: 401,
    createdBy: 'Sneha Gupta',
    createdAt: new Date('2024-01-14'),
    description: 'Insights on writing clean, maintainable code',
  },
  {
    id: 'r21',
    title: 'Kaggle - Data Science Competitions',
    link: 'https://kaggle.com',
    category: 'Course',
    tags: ['Data Science', 'Machine Learning', 'Competitions', 'Python'],
    upvotes: 367,
    createdBy: 'Sneha Gupta',
    createdAt: new Date('2024-02-06'),
    description: 'Learn data science through competitions and real datasets',
  },
  {
    id: 'r22',
    title: 'MDN Web Docs - JavaScript Guide',
    link: 'https://developer.mozilla.org/en-US/docs/Web/JavaScript',
    category: 'Docs',
    tags: ['JavaScript', 'Web Development', 'Reference'],
    upvotes: 389,
    createdBy: 'Admin',
    createdAt: new Date('2024-01-09'),
    description: 'Comprehensive JavaScript documentation and tutorials',
  },
  {
    id: 'r23',
    title: 'GitHub Student Developer Pack',
    link: 'https://education.github.com/pack',
    category: 'GitHub',
    tags: ['Student Resources', 'Free Tools', 'GitHub'],
    upvotes: 478,
    createdBy: 'Admin',
    createdAt: new Date('2024-01-07'),
    description: 'Free developer tools and services for students',
  },
  {
    id: 'r24',
    title: 'Awesome Interview Questions',
    link: 'https://github.com/DopplerHQ/awesome-interview-questions',
    category: 'GitHub',
    tags: ['Interview Prep', 'Questions', 'Career'],
    upvotes: 423,
    createdBy: 'Karthik Reddy',
    createdAt: new Date('2024-02-11'),
    description: 'Curated list of interview questions for various technologies',
  },
  {
    id: 'r25',
    title: 'Net Ninja - Modern Web Development',
    link: 'https://youtube.com/@NetNinja',
    category: 'YouTube',
    tags: ['Web Development', 'Tutorials', 'Modern Stack'],
    upvotes: 312,
    createdBy: 'Rahul Verma',
    createdAt: new Date('2024-01-26'),
    description: 'Clear, comprehensive tutorials on modern web technologies',
  },
  {
    id: 'r26',
    title: 'JavaScript.info - The Modern Tutorial',
    link: 'https://javascript.info',
    category: 'Docs',
    tags: ['JavaScript', 'Tutorial', 'Modern JavaScript'],
    upvotes: 356,
    createdBy: 'Arjun Sharma',
    createdAt: new Date('2024-02-09'),
    description: 'From basics to advanced topics with simple explanations',
  },
  {
    id: 'r27',
    title: 'Refactoring Guru - Design Patterns',
    link: 'https://refactoring.guru',
    category: 'Blog',
    tags: ['Design Patterns', 'Refactoring', 'Best Practices'],
    upvotes: 298,
    createdBy: 'Priya Patel',
    createdAt: new Date('2024-01-21'),
    description: 'Design patterns and refactoring explained with examples',
  },
];

export const mockAnalytics: AnalyticsData = {
  totalMatches: 47,
  avgCompatibility: 78,
  resourcesSaved: 23,
  skillsLearned: 12,
  weeklyActivity: [
    { day: 'Mon', matches: 5, resources: 3 },
    { day: 'Tue', matches: 8, resources: 5 },
    { day: 'Wed', matches: 12, resources: 7 },
    { day: 'Thu', matches: 6, resources: 4 },
    { day: 'Fri', matches: 10, resources: 8 },
    { day: 'Sat', matches: 15, resources: 12 },
    { day: 'Sun', matches: 11, resources: 6 },
  ],
  skillDistribution: [
    { skill: 'React', count: 85 },
    { skill: 'Python', count: 72 },
    { skill: 'Node.js', count: 64 },
    { skill: 'TypeScript', count: 58 },
    { skill: 'Machine Learning', count: 45 },
    { skill: 'AWS', count: 38 },
  ],
};

export const skillCategories = {
  frontend: ['React', 'Vue', 'Angular', 'Svelte', 'TypeScript', 'JavaScript', 'HTML', 'CSS', 'Tailwind CSS', 'Next.js'],
  backend: ['Node.js', 'Python', 'Django', 'Flask', 'Express', 'FastAPI', 'Ruby on Rails', 'Spring Boot', 'Go'],
  mobile: ['React Native', 'Flutter', 'Swift', 'Kotlin', 'Android', 'iOS'],
  database: ['PostgreSQL', 'MongoDB', 'MySQL', 'Redis', 'Firebase', 'Supabase'],
  devops: ['Docker', 'Kubernetes', 'AWS', 'Azure', 'GCP', 'CI/CD', 'Jenkins'],
  ai: ['Machine Learning', 'Deep Learning', 'TensorFlow', 'PyTorch', 'NLP', 'Computer Vision', 'OpenAI'],
  design: ['UI/UX Design', 'Figma', 'Adobe XD', 'Sketch', 'Photoshop'],
};

export const allSkills = Object.values(skillCategories).flat();